config/routes.rb
Rent::Application.routes.draw do
    
  resources :categories

  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end    
  
  root :to => "rents#index"
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/safety',  :to => 'pages#safety'
  match '/terms',   :to => 'pages#terms'
  match '/help',    :to => 'pages#help'
  match '/dashboard',    :to => 'pages#dashboard'
  match '/inbox',    :to => 'pages#inbox'
  match '/profile',    :to => 'pages#profile'
  match '/account',    :to => 'pages#account'
  match '/find',    :to => 'pages#find'
  match '/list',    :to => 'pages#list'
  match '/copyright',  :to => 'pages#copyright'
  match '/privacy',    :to => 'pages#privacy'
  match '/gitpush',    :to => 'pages#gitpush'      
  match '/how',    :to => 'pages#how'
  match '/rentals',    :to => 'pages#rentals'

              
  resources :stores do
    resources :items do
      resources :photos do
        collection do
          post 'sort'
        end
      end
    end
  end

  resources :stores
    
  resources :rents do
    collection do
      get 'search'
    end
  end
    
    
  resources :interests, :only => :new
  resources :interests, :only => :create
 
  resources :images, :only => :show
  
  match "/images/uploads/*path" => "gridfs#serve"
      

end

app/views/shared/_fb_root.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) {return;}
js = d.createElement(s); js.id = id;
<%= raw "js.src = '//connect.facebook.net/en_US/all.js#xfbml=1&appId=#{@fb_api_key}';" %>
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/shared/_menu.html.haml
%ul#navlist{}
  %li#find
    = link_to "Find Rentals", find_path
  %li#list
    = link_to  "List Rentals" , list_path
  %li#how
    = link_to  "How" , how_path

app/views/shared/_navigation.html.haml
#nav_list 
  - if user_signed_in? 
    %li
      - if current_user.fb_avatar_url != nil
        = link_to(image_tag(current_user.fb_avatar_url) + current_user.name, edit_user_registration_path)
      - else
        = link_to('My Account', edit_user_registration_path)
  - if user_signed_in? 
    %li
      = link_to('Log Out', destroy_user_session_path, :method=>'delete')    
  - else 
    %li
      #fb_signin
        = link_to(image_tag('fb_signin.png'), user_omniauth_authorize_path(:facebook) )
//        .fb-login-button{'data-show-faces' => "true", 'data-width' => "200", 'data-max-rows' => "1"}

 

app/views/shared/_store_item.html.haml
#homepage_item
 #item_result_picture
  - if !item.photos[0].nil?
   = link_to image_tag(item.photos[0].image.thumb.url), rent_path(item)
 #item_result_owner_picture
  - if ( item.store.use_fb_avatar? && item.store.user.fb_avatar_url?  ) 
   = link_to image_tag(item.store.user.fb_avatar_url), store_path(item.store)
  - else
   - if item.store.avatar?  
    = link_to image_tag(item.store.avatar.thumb.url), store_path(item.store)
 #item_result
  #item_result_details
   #item_result_price
    - if !item.cost.nil?
     = item.cost
   #item_result_text
    %h2
     = link_to item.title , rent_path(item)
    %p
     - if !item.zipcode.nil?
      = item.zipcode.city + ',' + item.zipcode.state + ' ' + item.zipcode.name
    %p Item.Reviews
    %p Item.Endorsements

app/views/shared/_store_search.html.haml
THIS IS THE SEARCH BAR :NYI

app/views/shared/_store_sidebar.html.haml
#temp_item_result_owner_picture
 %br/
 - if store.user.fb_name? && store.use_fb_name?
  = link_to store.user.fb_name, store_path(store)
 - else
  = link_to store.name, store_path(store)

 - if ( store.use_fb_avatar? && store.user.fb_avatar_url?  ) 
  = link_to image_tag(store.user.fb_avatar_url + '?type=large'), store_path(store)
 - else
  - if store.avatar?  
   = link_to image_tag(store.avatar.url), store_path(store)

%br/

- if store.user == current_user
 = link_to "Change image or name", edit_store_path(store)

app/views/shared/_user_sidebar.html.haml
#user_owner_picture
 - if ( store.use_fb_avatar? && store.user.fb_avatar_url?  ) 
  = link_to image_tag(user.fb_avatar_url + '?type=large'), store_path(store)
 - else
  - if store.avatar?  
   = link_to image_tag(store.avatar.url), store_path(store)


 %br/
 - if user.fb_name? 
  = link_to store.user.fb_name, store_path(store)
 - else
  = link_to store.name, store_path(store)


%br/

- if store.user == current_user
 = link_to "Change image or name", edit_store_path(store)

%br/
Reviews, <br/>Endorsements, <br/>Verifications

app/views/shared/_usergroup_item.html.haml
- if usergroup.all_fb_friends == true
  - if user.fb_id  
    -# = "All #{user.fb_friends.size} Facebook Friends"
    = "Facebook Friends"
  - else
    = "Facebook Friends "
    = link_to "(Log In)", "/users/auth/facebook"
- elsif usergroup.everyone
  = "Everyone"