config/routes.rb
Rent::Application.routes.draw do
    
  resources :categories

  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end    
  
  root :to => "rents#index"
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/safety',  :to => 'pages#safety'
  match '/terms',   :to => 'pages#terms'
  match '/help',    :to => 'pages#help'
  match '/dashboard',    :to => 'pages#dashboard'
  match '/inbox',    :to => 'pages#inbox'
  match '/profile',    :to => 'pages#profile'
  match '/account',    :to => 'pages#account'
  match '/find',    :to => 'pages#find'
  match '/list',    :to => 'pages#list'
  match '/copyright',  :to => 'pages#copyright'
  match '/privacy',    :to => 'pages#privacy'
  match '/gitpush',    :to => 'pages#gitpush'      
  match '/how',    :to => 'pages#how'
  match '/rentals',    :to => 'pages#rentals'

              
  resources :stores do
    resources :items do
      resources :photos do
        collection do
          post 'sort'
        end
      end
    end
  end

  resources :stores
    
  resources :rents do
    collection do
      get 'search'
    end
  end
    
    
  resources :interests, :only => :new
  resources :interests, :only => :create
 
  resources :images, :only => :show
  
  match "/images/uploads/*path" => "gridfs#serve"
      

end

app/models/item.rb
class Item 
  include Mongoid::Document
    attr_accessible :title, :description, :active, :location, :cost, :item_user_groups
  belongs_to :store
  field :title
  field :description
  field :active, type: Integer
  field :location
  field :cost
    
  has_and_belongs_to_many :item_user_groups, :class_name => "UserGroup" 

  
  belongs_to :zipcode, :inverse_of => nil
  embeds_many :photos  

  validates :title,  :presence => true,
                     :length   => { :maximum => 150 }
  validates :description, :presence => true

  before_save   :set_zipcode
    
    
  def set_default_access
    self.item_user_groups = [ UserGroup.all_fb_friends ]  
  end
    
  def set_zipcode
      # TODO: regex and find zipcode from address
      self.zipcode = Zipcode.where(name: self.location).first
       
  end
  
  def latlon
     set_zipcode
     if ( !self.zipcode.nil? )
       return self.zipcode.location
     end
     nil
  end
  
  def deactivate 
     self.active = 0
   end
   
   def activate 
     self.active = 1
   end
        
   def active?
     self.active == 1
   end
  
    
    def to_json
        result = Hash.new
        result[:id]          = self.id
        result[:title]       = self.title
        result[:description] = self.description
        result[:latlon]      = self.latlon
        result[:cost]       = self.cost
     
        result.to_json
    end
    
 end  

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  #controller for maintaining items
  
  before_filter :set_store
  # GET /items
  # GET /items.json
  def index

    if @store.nil? || @store.user_id != current_user.id
      redirect_to root_path
    else
      @items = @store.items
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @items }
      end
    end
    
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
    if @item.nil? || @item.store.user_id != current_user.id 
      redirect_to root_path
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @item }
      end
    end
    
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new
    @item.store = @store
    @item.activate
    @item.set_default_access
    @groups = [ UserGroup::everyone, UserGroup::all_fb_friends ]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end
  # GET /items/1/edit
  def edit
    if @store.nil? || @store.user_id != current_user.id
      redirect_to root_path
    else
    
    @item = Item.find(params[:id])
    @groups = [ UserGroup::everyone, UserGroup::all_fb_friends ]
        
    respond_to do |format|
       format.html
    end

  end
end

  # POST /items
  # POST /items.json
  def create
    if @store.nil? || @store.user_id != current_user.id
      redirect_to root_path
    else
    
    @item = Item.new(params[:item])
    @item.activate
    @item.item_user_groups = UserGroup.find( params[:group_ids] ) if params[:group_ids]
    @groups = [ UserGroup::everyone, UserGroup::all_fb_friends ]
    
    @item.store = @store
    respond_to do |format|
      if @item.save
        format.html    { redirect_to store_items_path(@store), notice: 'Item was successfully created.' }
        format.json    { render json: @item, status: :created, location: @item }
      else
        format.html {  render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
    end
    
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    if @store.nil? || @store.user_id != current_user.id
      redirect_to root_path
    else
    
    @item = Item.find(params[:id])
    @item.item_user_groups.clear
    @item.item_user_groups = UserGroup.find( params[:group_ids] ) if params[:group_ids]
        
    respond_to do |format|
      if @item.update_attributes(params[:item])
       format.html { redirect_to store_items_path(@store), notice: 'Item was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    if @store.nil? || @store.user_id != current_user.id
      redirect_to root_path
    else
    
      @item = Item.find(params[:id])
      @item.destroy

      respond_to do |format|
        format.html    { redirect_to store_items_path(@store) }
        format.json    { head :ok }
      end
    end
  end
  
  private
    def set_store
      if  !current_user.nil? 
        @store = Store.find_by_id_and_user(params[:store_id], current_user)
      end
    end

  
end

app/views/items/_form.html.erb
<%= form_for item, :url => iurl, :method => iact do |f| %>
<% if item.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

<ul>
<% item.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>
<div class="field">
<%= f.label :active %>
<%= f.check_box :active %>
</div>
<div class="field">
<%= f.label :cost %><br />
<%= f.text_field :cost %>
</div>
<div class="field">
<%= f.label "Zip Code" %><br />
<%= f.text_field :location %>
</div>
<div class="field">
<%= f.label :title %><br />
<%= f.text_field :title %>
</div>
<div class="field">
<%= f.label :description %><br />
<%= f.text_area :description, :cols => 100, :rows => 20  %>
</div>


<table>
<tr>
<td><b>Who can see your item</td>
</tr>
<% @groups.each do |g| %>
<tr>
<td>
<input type="checkbox" id="<%=g.id%>" name="group_ids[]" value="<%=g.id%>" 
<%if item.item_user_groups.include? g %> checked="checked" <% end %> >
<%= render :partial => "shared/usergroup_item", :locals => { :usergroup => g, :user => item.store.user } %>
</td>
</tr>
<% end %>
</table>

<div class="actions">
<%= f.submit %>
</div>
<% end %>

app/views/items/edit.android.erb
<h1>Editing item</h1>

<%= form_for @item, :url => store_item_path(@store,@item) do |f| %>
<% if @item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :description %><br />
  <%= f.text_field :description %>
</div>
<div class="field">
  <%= f.label :location %><br />
  <%= f.text_field :location %>
</div>
<div class="actions">
  <%= f.submit %>
</div>

<% end %>

<%= link_to 'Destroy', store_item_path(params[:store_id],@item), confirm: 'Are you sure?', method: :delete %></td>
<%= link_to 'Show', store_item_path(params[:store_id],@item) %> |
<%= link_to 'Items', store_items_path(params[:store_id]) %>

app/views/items/edit.html.haml
= render :partial => "shared/store_sidebar", :locals => { :store => @item.store }
= render :partial => "form", :locals => { :item => @item, :iurl => store_item_path(@store,@item), :iact => 'put' }

app/views/items/index.html.erb
<h2>My rentals</h2>

<table>
	
<% if @items.any? %>
	<tr>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>
 
<% @items.each do |item| %>
  <tr>
	<% if item.active? %>
     <td><%= link_to item.title , edit_store_item_path(@store,item) %></td>
	<% else %>
	      <td>  <del>  <%= link_to item.title , edit_store_item_path(@store,item) %>  <del>  </td>
	<% end %>

	<% if item.active? %>
	  </del>
	<% end %>  
  </tr>
<% end %>
<% end %>
<tr>
<td>
<form accept-charset="UTF-8" action="items/new" method="get" style="margin:0;padding:0;display:inline">
			<button  type="submit" value="newitem" style="float:left;"  >Add Rental</button>
</form></td>
</tr>

</table>

app/views/items/new.html.haml
= render :partial => "shared/store_sidebar", :locals => { :store => @item.store }
= render  :partial => "form", :locals => { :item => @item, :iurl => store_items_path(@item.store), :iact => 'post' }

app/views/items/show.android.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @item.description %>
</p>

<p>
  <b>Location:</b>
  <%= @item.location %>
</p>

<p>
  <b>Owner:</b>
  <%= @item.store.name %>
</p>


<%= link_to 'Edit', edit_store_item_path(@store,@item) %> |
<%= link_to 'Items', store_items_path(@store) %>

app/views/items/show.html.haml
%h1 Item

= link_to 'Edit', edit_store_item_path(@item.store, @item)
\|
= link_to 'Back', store_items_path(@item.store)
|
= link_to 'Add photo', new_store_item_photo_path(@item.store, @item)

%p
  %b Title:
  = @item.title
%p
  %b Body:
  = @item.description

%p
  %i Note: Photos are sortable. Just drag and drop into new position

.container
  .photos#sortable
    %h2 Photos

    - @item.photos.forward.each do |photo|
      = render photo

  .queue
    / This division is replaced with a flash button by Uploadify
    #photo_upload

/ Only load uploadify javascript on pages they are needed
= javascript_include_tag '/uploadify/swfobject.js', '/uploadify/jquery.uploadify.v2.1.0.min.js'

/ See application_helper.rb for this code
= photo_uploadify

/ And more Javascript
= javascript_include_tag 'jquery-ui.min'

/ application_helper
= photo_sortable