config/routes.rb
Rent::Application.routes.draw do
    
  resources :categories

  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end    
  
  root :to => "rents#index"
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/safety',  :to => 'pages#safety'
  match '/terms',   :to => 'pages#terms'
  match '/help',    :to => 'pages#help'
  match '/dashboard',    :to => 'pages#dashboard'
  match '/inbox',    :to => 'pages#inbox'
  match '/profile',    :to => 'pages#profile'
  match '/account',    :to => 'pages#account'
  match '/find',    :to => 'pages#find'
  match '/list',    :to => 'pages#list'
  match '/copyright',  :to => 'pages#copyright'
  match '/privacy',    :to => 'pages#privacy'
  match '/gitpush',    :to => 'pages#gitpush'      
  match '/how',    :to => 'pages#how'
  match '/rentals',    :to => 'pages#rentals'

              
  resources :stores do
    resources :items do
      resources :photos do
        collection do
          post 'sort'
        end
      end
    end
  end

  resources :stores
    
  resources :rents do
    collection do
      get 'search'
    end
  end
    
    
  resources :interests, :only => :new
  resources :interests, :only => :create
 
  resources :images, :only => :show
  
  match "/images/uploads/*path" => "gridfs#serve"
      

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Renters Swap</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
 
  <%= csrf_meta_tags %>

<script type="text/javascript">

var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-24711459-3']);
_gaq.push(['_trackPageview']);

(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();

</script>

</head>
<div id="fb-root"></div>
<script>
window.fbAsyncInit = function() {
FB.init({
appId      : '196690723742630', // App ID
channelURL : '//WWW.rentersswap.com/channel.html', // Channel File
status     : true, // check login status
cookie     : true, // enable cookies to allow the server to access the session
oauth      : true, // enable OAuth 2.0
xfbml      : true  // parse XFBML
});

// Additional initialization code here
};

// Load the SDK Asynchronously
(function(d){
var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
js = d.createElement('script'); js.id = id; js.async = true;
js.src = "//connect.facebook.net/en_US/all.js";
d.getElementsByTagName('head')[0].appendChild(js);
}(document));
</script>

<body>
<div id="pagewidth" > 
<div>
	  <div class='left'>
	  	    <div id="header_left">
<%= link_to image_tag('logo.png'), root_path %>
	  	    </div>
	  </div>

      <div class='right'>
	    <div id="header_right">
	      <ul class="hmenu">
            <%= render 'shared/navigation' %>
          </ul>
        </div>
      </div>
</div>

<%= yield %>


	<div id="footer" >
	   <br/>
	   <ul class="fmenu">
	   	   <li><%= link_to "Contact", "#" %></li>
	   	   <li><%= link_to "About", "#" %></li>
	   	   <li><%= link_to "Safety", "#" %></li>

	   	   	   	   <li><%= link_to "Terms and Conditions", "#" %></li>
	   	   	   	   <li><%= link_to "Help", "#" %></li>
	   </ul>
	</div>

</body>


</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      RentSwap.org
    = stylesheet_link_tag    "style"
    
    %link{:rel=>"shortcut icon", :href=>'/assets/favicon.ico' } 
    = javascript_include_tag "application"
    %link{:href => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css", :rel => "stylesheet" , :type => "text/css"}
    %script{ :src => "http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"}
    %script{:src => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js" }
    = csrf_meta_tags
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-24711459-3']);
  _gaq.push(['_trackPageview']);

  (function() {
  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

%div#fb-root
:javascript
  window.fbAsyncInit = function() {
  FB.init({
  appId      : '248876391827927', // App ID
  status     : true, // check login status
  cookie     : true, // enable cookies to allow the server to access the session
  oauth      : true, // enable OAuth 2.0
  xfbml      : true  // parse XFBML
  });

  // Additional initialization code here
  };

  // Load the SDK Asynchronously
  (function(d){
  var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
  js = d.createElement('script'); js.id = id; js.async = true;
  js.src = "//connect.facebook.net/en_US/all.js";
  d.getElementsByTagName('head')[0].appendChild(js);
  }(document));

%body
  #top
    #header
      = link_to image_tag('logo.png'), root_path
      #nav
        = render 'shared/navigation'
      %div#menu_wrapper
        = render 'shared/menu'
    -#%div#left-sidebar
    %div#container
      %div#content
        = yield
      %div#footer
        %ul.fmenu
          %li= link_to "Contact", contact_path
          %li= link_to "About", about_path
          %li= link_to "Safety", safety_path
          %li= link_to "Terms and Conditions", terms_path
          %li= link_to "Privacy", privacy_path
          %li= link_to "Copyright", copyright_path
          %li= link_to "Help", help_path

app/views/layouts/applicationold_html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Renters Swap</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>

  <%= csrf_meta_tags %>

<script type="text/javascript">

var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-24711459-3']);
_gaq.push(['_trackPageview']);

(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();

</script>

</head>
<div id="fb-root"></div>
<script>
window.fbAsyncInit = function() {
FB.init({
appId      : '196690723742630', // App ID
channelURL : '//WWW.rentersswap.com/channel.html', // Channel File
status     : true, // check login status
cookie     : true, // enable cookies to allow the server to access the session
oauth      : true, // enable OAuth 2.0
xfbml      : true  // parse XFBML
});

// Additional initialization code here
};

// Load the SDK Asynchronously
(function(d){
var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
js = d.createElement('script'); js.id = id; js.async = true;
js.src = "//connect.facebook.net/en_US/all.js";
d.getElementsByTagName('head')[0].appendChild(js);
}(document));
</script>



<body>
<div id="pagewidth" >

<div>


	  <div class='left'>
	  	    <div id="header_left">
<%= link_to image_tag('logo.png'), root_path %>
	  	    </div>
	  </div>

      <div class='right'>
	    <div id="header_right">
	      <ul class="hmenu">
            <%= render 'shared/navigation' %>
          </ul>
        </div>
      </div>
</div>

<%= yield %>


	<div id="footer" >
	   <br/>
	   <ul class="fmenu">
	   	   <li><%= link_to "Contact", "#" %></li>
	   	   <li><%= link_to "About", "#" %></li>
	   	   <li><%= link_to "Safety", "#" %></li>

	   	   	   	   <li><%= link_to "Terms and Conditions", "#" %></li>
	   	   	   	   <li><%= link_to "Help", "#" %></li>
	   </ul>
	</div>

</body>


</html>